FROM baselibrary/java:8
MAINTAINER ShawnMa <qsma@thoughtworks.com>

## Version
ENV TOMCAT_MAJOR   %%TOMCAT_MAJOR%%
ENV TOMCAT_VERSION %%TOMCAT_VERSION%%

## Packages
RUN \
  apt-get update &&\
  apt-get install -y tomcat%%TOMCAT_MAJOR%%=$TOMCAT_VERSION &&\
  rm -rf /var/lib/apt/lists/*
